version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hujing19960825
      MYSQL_USER: hujing
      MYSQL_PASSWORD: hujing19960825
      TZ: Hongkong
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/:/etc/mysql/conf.d/
